/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_serenade_treesitter_Node */

#ifndef _Included_ai_serenade_treesitter_Node
#define _Included_ai_serenade_treesitter_Node
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_serenade_treesitter_Node
 * Method:    getChildByFieldName
 * Signature: (Ljava/lang/String;)Lai/serenade/treesitter/Node;
 */
JNIEXPORT jobject JNICALL Java_ai_serenade_treesitter_Node_getChildByFieldName
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
